{% set name = "minver" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/adamralph/minver/archive/{{ version }}.tar.gz
  sha256: 1813ec9d8248d40403791c14fde0168eceff3754cada811afffd66ad7c3659c3

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - minver --help

about:
  home: https://github.com/adamralph/minver
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Minimalistic versioning using Git tags.
  dev_url: https://github.com/adamralph/minver

extra:
  recipe-maintainers:
    - danielnachun
