context:
  version: 6.0.0

package:
  name: minver
  version: ${{ version }}

source:
  url: https://github.com/adamralph/minver/archive/${{ version }}.tar.gz
  sha256: 1813ec9d8248d40403791c14fde0168eceff3754cada811afffd66ad7c3659c3

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - minver --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Minimalistic versioning using Git tags.
  homepage: https://github.com/adamralph/minver
  repository: https://github.com/adamralph/minver

extra:
  recipe-maintainers:
    - danielnachun
